language: objective-c
osx_image: xcode7.3

script:
  - xcodebuild test -workspace BrightFutures.xcworkspace -scheme BrightFutures-Mac
  - xcodebuild test -workspace BrightFutures.xcworkspace -scheme BrightFutures-iOS -sdk iphonesimulator
  - xcodebuild test -workspace BrightFutures.xcworkspace -scheme BrightFutures-tvOS -sdk appletvsimulator
  - xcodebuild build -workspace BrightFutures.xcworkspace -scheme BrightFutures-watchOS -sdk watchsimulator

notifications:
  email: true